### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by mckent05** [mckent05/Javascript_Capstone#21]
https://github.com/mckent05/Javascript_Capstone/projects/1

My partner @brytebee  and I @mckent05 have set up our kanban board for the capstone project

Student A has been assigned to @mckent05  while student B has been assigned to @brytebee

**Comment by omar-labana** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to start your project! 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
